a=int (input("enter a value for A:"))
b=int (input("enter b value for b:"))
print ("a=", a and "b=",b)
print("the a>b or a==b=",a>b or a==b)
print("then not a>b=",not a>b)
print("the a>b and a==b=" ,a>b and a==b)
